version = 4
final_space = true

[palette]
  blue = '#89B4FA'
  closer = 'p:os'
  lavender = '#B4BEFE'
  os = '#ACB0BE'
  pink = '#F5C2E7'

[upgrade]
  source = 'cdn'
  interval = '168h'
  auto = false
  notice = false

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = '{{ .Path }} '
    foreground = 'p:pink'
    type = 'path'
    style = 'plain'

    max_width=69

    [blocks.segments.options]
      folder_icon = '....'
      home_icon = '~'
      max_width=30
      style = 'powerlevel'
      display_root=true

  [[blocks.segments]]
    template = '{{ .Path }} '
    foreground = 'p:pink'
    type = 'path'
    style = 'plain'

    min_width=70
    max_width=99

    [blocks.segments.options]
      folder_icon = '....'
      home_icon = '~'
      max_width=40
      style = 'powerlevel'
      display_root=true

  [[blocks.segments]]
    template = '{{ .Path }} '
    foreground = 'p:pink'
    type = 'path'
    style = 'plain'

    min_width=100
    max_width=129

    [blocks.segments.options]
      folder_icon = '....'
      home_icon = '~'
      max_width=70
      style = 'powerlevel'
      display_root=true

  [[blocks.segments]]
    template = '{{ .Path }} '
    foreground = 'p:pink'
    type = 'path'
    style = 'plain'

    min_width=130

    [blocks.segments.options]
      folder_icon = '....'
      home_icon = '~'
      max_width=100
      style = 'powerlevel'
      display_root=true

  [[blocks.segments]]
    template = '{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }} '
    foreground = 'p:lavender'
    type = 'git'
    style = 'plain'

    [blocks.segments.options]
      branch_icon = ''
      cherry_pick_icon = ' '
      commit_icon = ' '
      fetch_status = true
      fetch_upstream_icon = false
      merge_icon = ' '
      no_commits_icon = ' '
      rebase_icon = ' '
      revert_icon = ' '
      tag_icon = ' '

  [[blocks.segments]]
    template = ''
    foreground = 'p:closer'
    type = 'text'
    style = 'plain'
