version = 4
final_space = true

[palette]
  blue = '#89B4FA'
  closer = 'p:os'
  lavender = '#B4BEFE'
  os = '#ACB0BE'
  pink = '#F5C2E7'
  red = '#f38ba8'
  green = '#a6e3a1'
  peach = '#fab387'

[upgrade]
  source = 'cdn'
  interval = '168h'
  auto = false
  notice = false

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '{{ .Path }} '
    foreground = 'p:pink'
    type = 'path'
    style = 'plain'

    max_width=69

    [blocks.segments.options]
      folder_icon = '....'
      home_icon = '~'
      max_width=30
      style = 'powerlevel'
      display_root=true

  [[blocks.segments]]
    template = '{{ .Path }} '
    foreground = 'p:pink'
    type = 'path'
    style = 'plain'

    min_width=70
    max_width=99

    [blocks.segments.options]
      folder_icon = '....'
      home_icon = '~'
      max_width=40
      style = 'powerlevel'
      display_root=true

  [[blocks.segments]]
    template = '{{ .Path }} '
    foreground = 'p:pink'
    type = 'path'
    style = 'plain'

    min_width=100
    max_width=129

    [blocks.segments.options]
      folder_icon = '....'
      home_icon = '~'
      max_width=70
      style = 'powerlevel'
      display_root=true

  [[blocks.segments]]
    template = '{{ .Path }} '
    foreground = 'p:pink'
    type = 'path'
    style = 'plain'

    min_width=130

    [blocks.segments.options]
      folder_icon = '....'
      home_icon = '~'
      max_width=100
      style = 'powerlevel'
      display_root=true

  [[blocks.segments]]
    template = '{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }} '
    foreground = 'p:lavender'
    type = 'git'
    style = 'plain'

    [blocks.segments.options]
      branch_icon = ''
      cherry_pick_icon = ' '
      commit_icon = ' '
      fetch_status = true
      fetch_upstream_icon = false
      merge_icon = ' '
      no_commits_icon = ' '
      rebase_icon = ' '
      revert_icon = ' '
      tag_icon = ' '

[[blocks]]
  type = "rprompt"

  [[blocks.segments]]
    type = "python"
    style = "plain"
    background = 'transparent'
    foreground = 'p:peach'
    template = '{{ if .Venv }} {{ .Venv }}{{ else }}{{ end }} <p:os>|</>'

    [blocks.segments.options]
      display_mode = "context"

  [[blocks.segments]]
    type = "status"
    style = "plain"
    background = 'transparent'
    foreground_templates = [
      "{{if gt .Code 0}}p:red{{end}}",
      "{{if eq .Code 0}}p:green{{end}}",
    ]
    template = "{{ if eq .Code 0 }}{{ else }} {{ .Code }}{{ end }}"

    [blocks.segments.options]
      always_enabled = true


[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    foreground_templates = [
      "{{if gt .Code 0}}p:red{{end}}",
      "{{if eq .Code 0}}p:closer{{end}}",
    ]
    template = ''
    type = 'text'
    style = 'plain'

[transient_prompt]
  foreground_templates = [
    "{{if gt .Code 0}}p:red{{end}}",
    "{{if eq .Code 0}}p:closer{{end}}",
  ]
  background = 'transparent'
  template = ' '

